### PR TITLE
Support GraphQL 3.0.0-preview-1547 up

### PR DESCRIPTION
**Pull request by benmccallum**
Bumps dependency on GraphQL to support namespace change of IResolveFieldContext classes in graphql-dotnet/graphql-dotnet@ca3b754

### CODE REVIEW

**Comment by benmccallum** [comment]
Hey @SimonCropp, running into incompatibilities again as there's been more namespace changes. If you could get a beta 2 out that'd be greatly appreciated. Thanks!

**Comment by benmccallum** [comment]
Hmm, I've just noticed the failed build. I fixed with a NuGet.config, but I'm thinking we shouldn't tie to myget, so I'll undo that and pin to a min version that made it into NuGet proper.

**Comment by benmccallum** [comment]
Nope, scrap that, there isn't one on NuGet at 1547 or higher. 
Might have to take a dependency on myget feed... unless the guys get can another NuGet preview release out, cc: @sungam3r / @joemcbride

**Comment by sungam3r** [comment]
See #215 
изображение

**Comment by sungam3r** [comment]
#215 include your changes

**Comment by benmccallum** [comment]
Feel free to close this then Joe; if you can merge the other one that is. If you're not sure about merging the other one yet though, I'd be grateful if you could merge this in the meantime. Happy Easter

**Pull request closed without merging**
