### PR TITLE
feat: Support GraphQL's new IResolveFieldContext

### LINKED ISSUE #184: Extension methods off IResolveFieldContext now
#### Is the feature request related to a problem

A recent [GraphQL PR](https://github.com/graphql-dotnet/graphql-dotnet/pull/1441) that was merged now means that resolvers are given the interface `IResolveFieldContext` or `IResolveFieldContext<T>` rather than the concrete type.

#### Describe the solution

We'll need to update the extension methods in this project to extend the interface instead now.
In fact, since `IResolveFieldContext<T>` inherits `IResolveFieldContext<T>`, we potentially can get rid of the duplication of the extensions.

#### Describe alternatives considered

Temporary workaround (in my own code) is to have wrapping extension methods that just internally cast to the concrete and then use the existing methods in here off that. I'm not using any different context types, so it doesn't bother me atm.

#### Additional context

N/A.

### PR DESCRIPTION
**Pull request by benmccallum**
Fixes #184

### CODE REVIEW

**Comment by benmccallum** [comment]
Let me know what your thoughts are on getting this released or if you don't want to just yet so I can figure out what we do for our needs.

**Comment by benmccallum** [comment]
PS. I've referenced this project locally in my graph sln and the problem with the missing method went away.

**Comment by SimonCropp** [comment]
This is now deployed. NuGet may take some time to make it available for download. i gave it a 4.0.0-beta1 version. sorry for the delay

**Comment by benmccallum** [comment]
No worries, thanks for that!

**Pull request merged**
